
dist: xenial

language: node_js
install:
  - npm install
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: heroku
  app: decide-stats-visualizer
  strategy: git
  api_key: 61e3e1ba-023e-42e3-89cf-867077b94b83