
dist: xenial

language: node_js
install:
  - npm install
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
branches:
  only:
  - master
deploy:
  provider: heroku
  app: decide-stats-visualizer
  strategy: git
  api_key: $HEROKU_API_KEY
