
dist: xenial

language: node_js
install:
  - npm install
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - |
    touch .env
    echo REACT_APP_API_ENDPOINT="$API_ENDPOINT" >> .env
    cat .env
  - npm run build
  - npm test
branches:
  only:
  - master
deploy:
  provider: script
  skip_cleanup: true
  image: ruby:latest
  script:
    - gem install dpl && gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=decide-stats-visualizer --api-key=$HEROKU_API_KEY