
dist: xenial

language: node_js
install:
  - npm install
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - |
    touch .env
    echo REACT_APP_API_ENDPOINT="$API_ENDPOINT" >> .env
    cat .env
  - npm run build
  - npm test
branches:
  only:
  - manoutbar
deploy_staging:
  stage: deploy
  type: deploy
  image: ruby:latest
  script:
  # workaround https://github.com/travis-ci/dpl/issues/1247
  - gem install dpl && gem install faraday -v 1.8.0
  - dpl --provider=heroku --app=decide-stats-visualizer --api-key=$HEROKU_API_KEY
  except:
  - schedules